### PR TITLE
Build with clang instead of gcc

### PR DESCRIPTION
**Pull request by bnoordhuis**
We may be hitting a compiler bug that is causing segfaults in production so see if switching compilers makes the problem go away.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
>  Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

Not a seamless upgrade then :facepalm:

**Comment by lloeki** [comment]
@bnoodrhuis You don't have to change build-libv8, just make clang available (e.g in Dockerfiles) and it'll favour clang over GCC.There are a couple of commits before that tried that.On 13 Sep 2024, at 20:22, Ben Noordhuis ***@***.***> wrote:﻿We may be hitting a compiler bug that is causing segfaults in production so see if switching compilers makes the problem go away.



You can view, comment on, or merge this pull request online at:
  https://github.com/rubyjs/libv8-node/pull/61

Commit Summary

  14d0459  Build with clang instead of gcc


File Changes  (1 file)

  
    M
    libexec/build-libv8
    (2)
  


Patch Links:

  https://github.com/rubyjs/libv8-node/pull/61.patch
  https://github.com/rubyjs/libv8-node/pull/61.diff

**Comment by SamSaffron** [comment]
yeah @lloeki coaxing this to use clang is not super easy... I thing platform also insists on using GCC here:

https://github.com/rubyjs/libv8-node/blob/7249c5d4ddedea049fa2b8005bd89877ad570887/libexec/platform#L100-L107

We may need to edit this as well ... I changed the container now ... but looking at build log from previous commit ... no clang yet 

May change these lines next

**Comment by SamSaffron** [comment]
image

**Comment by bnoordhuis** [comment]
> We may need to edit this as well ... I changed the container now ... but looking at build log from previous commit ... no clang yet

It's curious how it uses clang++ for some things and `ccache x86_64-linux-gnu-g++` for others. I'll look into it.

**Pull request merged**
