### PR TITLE
Port fixes from node-16 branch to node 17

### PR DESCRIPTION
**Pull request by seanmakesgames**

### CODE REVIEW

**Comment by seanmakesgames** [comment]
@lloeki @SamSaffron 
Failures on this run:
- 2 in 2.7
- 1 in ruby test 3.1:
https://github.com/seanmakesgames/libv8-node/actions/runs/3990378667/jobs/6846869586

```
In file included from ../deps/v8/src/heap/cppgc/prefinalizer-handler.cc:5:
../deps/v8/src/heap/cppgc/prefinalizer-handler.h: In member function 'size_t cppgc::internal::PreFinalizerHandler::ExtractBytesAllocatedInPrefinalizers()':
../deps/v8/src/heap/cppgc/prefinalizer-handler.h:32:17: error: 'exchange' is not a member of 'std'
```

**Comment by Fayti1703** [comment]
2.7 failures look like ye olde bundler libc detection problem.

**Comment by Fayti1703** [comment]
482ac9c8 fixes the Ruby test in 3.1. I expect that change to be specific to this version of node.

**Comment by lloeki** [comment]
> 2.7 failures look like ye olde bundler libc detection problem.

this should be fixable by updating rubygems+bundler. if not then there may be an upstream regression.

**Comment by seanmakesgames** [comment]
> > 2.7 failures look like ye olde bundler libc detection problem.
> 
> this should be fixable by updating rubygems+bundler. if not then there may be an upstream regression.

Are you doing this? Where do we update this?
I was never quite sure on which version pair for those- Is this a change in build.yml? I don't see a bundler version specified in there-

Maybe you can just make the change so we can see where that is controlled.

**Comment by lloeki** [comment]
Yeah I can make the change later today

**Comment by lloeki** [comment]
I pushed a bunch of commits to `node-16` that makes CI green, one of them being about pinning rubygems. Probably these should be cherry-picked over here too.

**Comment by Fayti1703** [comment]
(Note to self: Primary commits are 0fad62766de5eb1321b7e298670842904e672e9c & 4db6396edce91a5c17224c7c41a4b514dea1c85e)

**Comment by Fayti1703** [comment]
I've dropped the change in `ext/libv8-node/extconf.rb` from 4db6396edce91a5c17224c7c41a4b514dea1c85e, since this branch doesn't yet have the Truffleruby dummy Makefile generation in.

**Comment by Fayti1703** [comment]
CI is almost entirely green, with a failure on darwin test due to the GC test: <https://github.com/seanmakesgames/libv8-node/actions/runs/4009651664/jobs/6887267190>

I think this is a transient failure, though. Probably something to do with how the V8 GC was feeling that run.

**Comment by seanmakesgames** [comment]
@SamSaffron @lloeki 
CI is 100% green here:
https://github.com/seanmakesgames/libv8-node/actions/runs/4009651664

Can we get a merge?

**Comment by lloeki** [comment]
Done!

**Comment by SamSaffron** [comment]
wow looking amazing! how far are we from a new release here? Should we move 17 branch to main ? it is weird that the cutting edge is tucked away in a branch.

**Comment by seanmakesgames** [comment]
Completely agree @SamSaffron - though are we stopping at 17 or going to 18?

**Comment by SamSaffron** [comment]
would love a go at 18 :heart:

**Comment by seanmakesgames** [comment]
Looks like there's already a branch for 18; we'll do another rebase

**Comment by seanmakesgames** [comment]
Was just about to make a PR from 18 to master, but I'd love for us to change master to `main` beforehand -- Can one of you make that change? @SamSaffron @lloeki

**Comment by lloeki** [comment]
On this project I don't merge into `master`, so:

- Updated `master` to point to last `node-18` commit
- Created `node-19` branch

> I'd love for us to change `master` to `main`

This is a separate matter, please open a dedicated issue for that (one on `libv8-node` and one on `mini_racer`)

**Pull request merged**
