### PR TITLE
Update to node v17.3.1

### PR DESCRIPTION
**Pull request by nightpool**
This also includes a performance improvement for the build_monolith.sh script, which is to invoke `ar` once with all of the libraries to be included, rather then building it incrementally. Because of how ar creates a copy of the archive to update rather then updating the archive file in place, this speeds up the creation of the archive file *significantly* (When building with debug symbols, build_monolith.sh *alone* was taking >12 hours, and now takes 30ish minutes).

### CODE REVIEW

**Comment by lloeki** [comment]
Thanks for this update @nightpool!

**Comment by lloeki** [comment]
> invoke ar once with all of the libraries to be included, rather then building it incrementally

I can't recall why I did that, I think it was when trying to debug some specific symbol missing situations, and then having split `ar` calls made them appear for some reason.

**Comment by lloeki** [comment]
Yup, plans indeed, it's just that I had to pull off some  double shifts last month to reach some goals.

So plans are a) recover a bit from that b) build and push missing aarch64 musl lib and a new fat libc+musl c) build and push 17.x d) get aarch64 musl cross compiling sorted out

**Comment by SamSaffron** [comment]
@lloeki any chance we can do a release? perhaps we can add @nightpool to the rotation of people who can do the releases to decrease bus factor?

**Comment by lloeki** [comment]
I'm AFK til next week (checking things on phone), I'll do the release then and add @nightpool as suggested.

**Pull request merged**
